# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Dhiraj Kumar Singh
title: Doctoral researcher @ UL
email: dhirajkumar.singh@ul.ie
Address: Dublin 8, Ireland

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  dhirajLERO

linkedin_username: dhiraj-singh-b6a8a51b7

orcid_username: 0000-0002-5301-3724




# About Section
# about_title: About Me
about_profile_image: images/Headshot.jpg
about_content: | # this will include new lines to allow paragraphs
  A curious and passionate researcher with the hunger to make an impact and who takes pride in solving problems using data. With a research background in multidisciplinary computational and physical fields of science, my research interests include open, emerging technologies such as artificial intelligence, blockchain, and augmented reality, as well as their management and technological forecasting. My primary research focusses in the AI domain includes <mark>Multimodal networks</mark> and <mark>Explainable AI</mark>.


content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        sub_title: PhD in Explainable Artificial Intelligence
        caption: 2023 - 2027
        link: https://lero.ie/people/dhiraj-kumar-singh
        description: | # this will include new lines to allow paragraphs
          <mark>Centre for research and Training in AI</mark>, University of Limerick, Limerick, Ireland
          
          Member, <mark>Biocomputing and Development Systems Group </mark>, LERO, Research Ireland Centre for Software
      - layout: left
        sub_title: Lectureship
        caption: 2019
        link: https://ugcnet.nta.nic.in/
        description: | # this will include new lines to allow paragraphs
          University Grant Commission, <mark>NET (National Eligibility test)</mark>, India. 
          
          Lectureship Subject: Computer Science. Percentile: 98.01%
      - layout: left
        sub_title: Master’s Degree (M.Sc)
        caption: 2017 - 2019
        link: https://www.du.ac.in/
        description: | # this will include new lines to allow paragraphs
          <mark>University of Delhi<mark>, Delhi, India.
          
          Major: Informatics. CGPA: 7.39
          
          Advisor: Dr. Sanjiv Singh, Conducted Lectures on Machine Learning For M.Sc. Students.
      - layout: left
        sub_title: Bachelor's Degree (B.Sc Triple Major)
        caption: 2017 - 2019
        link: https://www.christuniversity.in/
        description: | # this will include new lines to allow paragraphs
          <mark>Christ University<mark>, Bangalore.
          
          Major: Mathematics, Physics And Electronics. CGPA: 8.25
          
          Conducted Lectures on Superconductors For B.Sc. Students.
  

  - title: Teaching Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        sub_title: Teaching Assistant
        caption: Spring 2025
        description: | # this will include new lines to allow paragraphs
          Software Development Project, University of Limerick, Ireland.
          
          The course guided bachelor students through the end-to-end process of designing and developing a web application. Students gained hands-on experience with front-end technologies such as HTML, CSS, and Bootstrap, as well as back-end development using PHP and MySQL.
          
          
          
      
  
  

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Harvard University
        caption: 2010 - 2013
        sub_title: BSc Computer Science
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
